# Generated by Django 3.1.1 on 2020-10-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=20)),
                ('domb', models.CharField(max_length=2)),
                ('domr', models.CharField(max_length=3)),
            ],
        ),
    ]
